FROM golang:1.25.7-alpine AS evmd-builder

WORKDIR /src

RUN apk add --no-cache curl build-base git bash file linux-headers eudev-dev make jq

COPY go.mod go.sum* ./
RUN go mod download

COPY . .
RUN LEDGER_ENABLED=false COSMOS_BUILD_OPTIONS="staticlink" BUILD_TAGS=muslc make build

FROM alpine:latest

RUN apk add --no-cache bash curl jq
COPY --from=evmd-builder /src/build/evmd /usr/local/bin/evmd

