// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/auction/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgConfirmAuction confirms an auction result on-chain.
type MsgConfirmAuction struct {
	AuctionId string `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Seller    string `protobuf:"bytes,2,opt,name=seller,proto3" json:"seller,omitempty"`
	Winner    string `protobuf:"bytes,3,opt,name=winner,proto3" json:"winner,omitempty"`
	Price     string `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Denom     string `protobuf:"bytes,5,opt,name=denom,proto3" json:"denom,omitempty"`
	EndHeight int64  `protobuf:"varint,6,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	AskSig    string `protobuf:"bytes,7,opt,name=ask_sig,json=askSig,proto3" json:"ask_sig,omitempty"`
	BidSig    string `protobuf:"bytes,8,opt,name=bid_sig,json=bidSig,proto3" json:"bid_sig,omitempty"`
	SellerSig string `protobuf:"bytes,9,opt,name=seller_sig,json=sellerSig,proto3" json:"seller_sig,omitempty"`
}

func (m *MsgConfirmAuction) Reset()         { *m = MsgConfirmAuction{} }
func (m *MsgConfirmAuction) String() string { return proto.CompactTextString(m) }
func (*MsgConfirmAuction) ProtoMessage()    {}
func (*MsgConfirmAuction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f06a4e4968adb4f, []int{0}
}
func (m *MsgConfirmAuction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfirmAuction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfirmAuction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfirmAuction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfirmAuction.Merge(m, src)
}
func (m *MsgConfirmAuction) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfirmAuction) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfirmAuction.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfirmAuction proto.InternalMessageInfo

type MsgConfirmAuctionResponse struct {
}

func (m *MsgConfirmAuctionResponse) Reset()         { *m = MsgConfirmAuctionResponse{} }
func (m *MsgConfirmAuctionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgConfirmAuctionResponse) ProtoMessage()    {}
func (*MsgConfirmAuctionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f06a4e4968adb4f, []int{1}
}
func (m *MsgConfirmAuctionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConfirmAuctionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConfirmAuctionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConfirmAuctionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConfirmAuctionResponse.Merge(m, src)
}
func (m *MsgConfirmAuctionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgConfirmAuctionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConfirmAuctionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConfirmAuctionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgConfirmAuction)(nil), "cosmos.auction.v1.MsgConfirmAuction")
	proto.RegisterType((*MsgConfirmAuctionResponse)(nil), "cosmos.auction.v1.MsgConfirmAuctionResponse")
}

func init() { proto.RegisterFile("cosmos/auction/v1/tx.proto", fileDescriptor_2f06a4e4968adb4f) }

var fileDescriptor_2f06a4e4968adb4f = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x3f, 0x8f, 0xda, 0x30,
	0x18, 0x87, 0x63, 0x28, 0xd0, 0x78, 0x68, 0x45, 0x84, 0x4a, 0x9a, 0x42, 0x8a, 0xa2, 0x56, 0x42,
	0xa8, 0x8a, 0x45, 0xbb, 0x75, 0xa9, 0xda, 0x2e, 0xed, 0xc0, 0x02, 0x5b, 0x17, 0x94, 0x3f, 0xae,
	0xb1, 0x20, 0x76, 0x14, 0x07, 0x4a, 0xb7, 0x8a, 0x89, 0xad, 0x95, 0x3a, 0x74, 0xed, 0x47, 0xe0,
	0x63, 0xdc, 0x88, 0x74, 0xcb, 0x8d, 0x27, 0x38, 0x89, 0xaf, 0x71, 0xb2, 0x1d, 0x6e, 0xb8, 0x2c,
	0xb7, 0xf9, 0x7d, 0x9e, 0xd7, 0xef, 0x2f, 0x76, 0x0c, 0x9d, 0x88, 0x8b, 0x84, 0x0b, 0x14, 0x2c,
	0xa3, 0x9c, 0x72, 0x86, 0x56, 0x43, 0x94, 0xaf, 0xfd, 0x34, 0xe3, 0x39, 0xb7, 0x9a, 0xda, 0xf9,
	0x85, 0xf3, 0x57, 0x43, 0xa7, 0x5d, 0xb4, 0x27, 0x82, 0xc8, 0xd6, 0x44, 0x10, 0xdd, 0xeb, 0x74,
	0x08, 0xe7, 0x64, 0x81, 0x51, 0x90, 0x52, 0x14, 0x30, 0xc6, 0xf3, 0x40, 0x6e, 0x11, 0x85, 0x6d,
	0x11, 0x4e, 0xb8, 0x5a, 0x22, 0xb9, 0xd2, 0xd4, 0xfb, 0x5d, 0x81, 0xcd, 0x91, 0x20, 0x9f, 0x39,
	0xfb, 0x4e, 0xb3, 0xe4, 0xa3, 0x4e, 0xb1, 0xba, 0x10, 0x16, 0x81, 0x53, 0x1a, 0xdb, 0xa0, 0x07,
	0xfa, 0xe6, 0xd8, 0x2c, 0xc8, 0xd7, 0xd8, 0x7a, 0x06, 0xeb, 0x02, 0x2f, 0x16, 0x38, 0xb3, 0x2b,
	0x4a, 0x15, 0x95, 0xe4, 0x3f, 0x28, 0x63, 0x38, 0xb3, 0xab, 0x9a, 0xeb, 0xca, 0x6a, 0xc1, 0x5a,
	0x9a, 0xd1, 0x08, 0xdb, 0x8f, 0x14, 0xd6, 0x85, 0xa4, 0x31, 0x66, 0x3c, 0xb1, 0x6b, 0x9a, 0xaa,
	0x42, 0x46, 0x63, 0x16, 0x4f, 0x67, 0x98, 0x92, 0x59, 0x6e, 0xd7, 0x7b, 0xa0, 0x5f, 0x1d, 0x9b,
	0x98, 0xc5, 0x5f, 0x14, 0xb0, 0xda, 0xb0, 0x11, 0x88, 0xf9, 0x54, 0x50, 0x62, 0x37, 0x74, 0x46,
	0x20, 0xe6, 0x13, 0x4a, 0xa4, 0x08, 0x69, 0xac, 0xc4, 0x63, 0x2d, 0x42, 0x1a, 0x4b, 0xd1, 0x85,
	0x50, 0x7f, 0x9e, 0x72, 0xa6, 0x3e, 0x8b, 0x26, 0x13, 0x4a, 0xde, 0x3f, 0xdd, 0xfe, 0x7f, 0x69,
	0x6c, 0x4e, 0xbb, 0x41, 0x71, 0x08, 0xef, 0x05, 0x7c, 0x5e, 0xba, 0x90, 0x31, 0x16, 0x29, 0x67,
	0x02, 0xbf, 0xfd, 0x07, 0x60, 0x75, 0x24, 0x88, 0xb5, 0x05, 0xf0, 0xc9, 0xbd, 0x3b, 0x7b, 0xe5,
	0x97, 0x7e, 0x95, 0x5f, 0x1a, 0xe4, 0xbc, 0x79, 0x48, 0xd7, 0x39, 0xce, 0xf3, 0x36, 0x97, 0x37,
	0x7f, 0x2b, 0x1d, 0xcf, 0x41, 0xe5, 0x27, 0x12, 0xe9, 0x2d, 0x4e, 0xed, 0xd7, 0x69, 0x37, 0x00,
	0x9f, 0x3e, 0x5c, 0x1c, 0x5c, 0xb0, 0x3f, 0xb8, 0xe0, 0xfa, 0xe0, 0x82, 0x3f, 0x47, 0xd7, 0xd8,
	0x1f, 0x5d, 0xe3, 0xea, 0xe8, 0x1a, 0xdf, 0x5e, 0x13, 0x9a, 0xcf, 0x96, 0xa1, 0x1f, 0xf1, 0xe4,
	0x3c, 0x06, 0xaf, 0x12, 0xb4, 0xbe, 0x1b, 0x96, 0xff, 0x4c, 0xb1, 0x08, 0xeb, 0xea, 0x41, 0xbc,
	0xbb, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xce, 0x10, 0xf8, 0x2f, 0x8e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ConfirmAuction(ctx context.Context, in *MsgConfirmAuction, opts ...grpc.CallOption) (*MsgConfirmAuctionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ConfirmAuction(ctx context.Context, in *MsgConfirmAuction, opts ...grpc.CallOption) (*MsgConfirmAuctionResponse, error) {
	out := new(MsgConfirmAuctionResponse)
	err := c.cc.Invoke(ctx, "/cosmos.auction.v1.Msg/ConfirmAuction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ConfirmAuction(context.Context, *MsgConfirmAuction) (*MsgConfirmAuctionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ConfirmAuction(ctx context.Context, req *MsgConfirmAuction) (*MsgConfirmAuctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmAuction not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ConfirmAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConfirmAuction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ConfirmAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmos.auction.v1.Msg/ConfirmAuction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ConfirmAuction(ctx, req.(*MsgConfirmAuction))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmos.auction.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfirmAuction",
			Handler:    _Msg_ConfirmAuction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmos/auction/v1/tx.proto",
}

func (m *MsgConfirmAuction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfirmAuction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfirmAuction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SellerSig) > 0 {
		i -= len(m.SellerSig)
		copy(dAtA[i:], m.SellerSig)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SellerSig)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.BidSig) > 0 {
		i -= len(m.BidSig)
		copy(dAtA[i:], m.BidSig)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BidSig)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.AskSig) > 0 {
		i -= len(m.AskSig)
		copy(dAtA[i:], m.AskSig)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AskSig)))
		i--
		dAtA[i] = 0x3a
	}
	if m.EndHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.EndHeight))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Price) > 0 {
		i -= len(m.Price)
		copy(dAtA[i:], m.Price)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Price)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Winner) > 0 {
		i -= len(m.Winner)
		copy(dAtA[i:], m.Winner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Winner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Seller) > 0 {
		i -= len(m.Seller)
		copy(dAtA[i:], m.Seller)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Seller)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AuctionId) > 0 {
		i -= len(m.AuctionId)
		copy(dAtA[i:], m.AuctionId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AuctionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgConfirmAuctionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConfirmAuctionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConfirmAuctionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgConfirmAuction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AuctionId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Seller)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Winner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Price)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EndHeight != 0 {
		n += 1 + sovTx(uint64(m.EndHeight))
	}
	l = len(m.AskSig)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BidSig)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SellerSig)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgConfirmAuctionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgConfirmAuction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfirmAuction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfirmAuction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuctionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Winner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Winner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Price = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndHeight", wireType)
			}
			m.EndHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AskSig", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AskSig = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BidSig", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BidSig = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellerSig", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SellerSig = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConfirmAuctionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConfirmAuctionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConfirmAuctionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
