// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package auctionv1

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Auction                  protoreflect.MessageDescriptor
	fd_Auction_auction_id       protoreflect.FieldDescriptor
	fd_Auction_seller           protoreflect.FieldDescriptor
	fd_Auction_winner           protoreflect.FieldDescriptor
	fd_Auction_price            protoreflect.FieldDescriptor
	fd_Auction_denom            protoreflect.FieldDescriptor
	fd_Auction_end_height       protoreflect.FieldDescriptor
	fd_Auction_ask_sig          protoreflect.FieldDescriptor
	fd_Auction_bid_sig          protoreflect.FieldDescriptor
	fd_Auction_seller_sig       protoreflect.FieldDescriptor
	fd_Auction_confirmed_height protoreflect.FieldDescriptor
	fd_Auction_tx_hash          protoreflect.FieldDescriptor
)

func init() {
	file_cosmos_auction_v1_auction_proto_init()
	md_Auction = File_cosmos_auction_v1_auction_proto.Messages().ByName("Auction")
	fd_Auction_auction_id = md_Auction.Fields().ByName("auction_id")
	fd_Auction_seller = md_Auction.Fields().ByName("seller")
	fd_Auction_winner = md_Auction.Fields().ByName("winner")
	fd_Auction_price = md_Auction.Fields().ByName("price")
	fd_Auction_denom = md_Auction.Fields().ByName("denom")
	fd_Auction_end_height = md_Auction.Fields().ByName("end_height")
	fd_Auction_ask_sig = md_Auction.Fields().ByName("ask_sig")
	fd_Auction_bid_sig = md_Auction.Fields().ByName("bid_sig")
	fd_Auction_seller_sig = md_Auction.Fields().ByName("seller_sig")
	fd_Auction_confirmed_height = md_Auction.Fields().ByName("confirmed_height")
	fd_Auction_tx_hash = md_Auction.Fields().ByName("tx_hash")
}

var _ protoreflect.Message = (*fastReflection_Auction)(nil)

type fastReflection_Auction Auction

func (x *Auction) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Auction)(x)
}

func (x *Auction) slowProtoReflect() protoreflect.Message {
	mi := &file_cosmos_auction_v1_auction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Auction_messageType fastReflection_Auction_messageType
var _ protoreflect.MessageType = fastReflection_Auction_messageType{}

type fastReflection_Auction_messageType struct{}

func (x fastReflection_Auction_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Auction)(nil)
}
func (x fastReflection_Auction_messageType) New() protoreflect.Message {
	return new(fastReflection_Auction)
}
func (x fastReflection_Auction_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Auction
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Auction) Descriptor() protoreflect.MessageDescriptor {
	return md_Auction
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Auction) Type() protoreflect.MessageType {
	return _fastReflection_Auction_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Auction) New() protoreflect.Message {
	return new(fastReflection_Auction)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Auction) Interface() protoreflect.ProtoMessage {
	return (*Auction)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Auction) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.AuctionId != "" {
		value := protoreflect.ValueOfString(x.AuctionId)
		if !f(fd_Auction_auction_id, value) {
			return
		}
	}
	if x.Seller != "" {
		value := protoreflect.ValueOfString(x.Seller)
		if !f(fd_Auction_seller, value) {
			return
		}
	}
	if x.Winner != "" {
		value := protoreflect.ValueOfString(x.Winner)
		if !f(fd_Auction_winner, value) {
			return
		}
	}
	if x.Price != "" {
		value := protoreflect.ValueOfString(x.Price)
		if !f(fd_Auction_price, value) {
			return
		}
	}
	if x.Denom != "" {
		value := protoreflect.ValueOfString(x.Denom)
		if !f(fd_Auction_denom, value) {
			return
		}
	}
	if x.EndHeight != int64(0) {
		value := protoreflect.ValueOfInt64(x.EndHeight)
		if !f(fd_Auction_end_height, value) {
			return
		}
	}
	if x.AskSig != "" {
		value := protoreflect.ValueOfString(x.AskSig)
		if !f(fd_Auction_ask_sig, value) {
			return
		}
	}
	if x.BidSig != "" {
		value := protoreflect.ValueOfString(x.BidSig)
		if !f(fd_Auction_bid_sig, value) {
			return
		}
	}
	if x.SellerSig != "" {
		value := protoreflect.ValueOfString(x.SellerSig)
		if !f(fd_Auction_seller_sig, value) {
			return
		}
	}
	if x.ConfirmedHeight != int64(0) {
		value := protoreflect.ValueOfInt64(x.ConfirmedHeight)
		if !f(fd_Auction_confirmed_height, value) {
			return
		}
	}
	if x.TxHash != "" {
		value := protoreflect.ValueOfString(x.TxHash)
		if !f(fd_Auction_tx_hash, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Auction) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "cosmos.auction.v1.Auction.auction_id":
		return x.AuctionId != ""
	case "cosmos.auction.v1.Auction.seller":
		return x.Seller != ""
	case "cosmos.auction.v1.Auction.winner":
		return x.Winner != ""
	case "cosmos.auction.v1.Auction.price":
		return x.Price != ""
	case "cosmos.auction.v1.Auction.denom":
		return x.Denom != ""
	case "cosmos.auction.v1.Auction.end_height":
		return x.EndHeight != int64(0)
	case "cosmos.auction.v1.Auction.ask_sig":
		return x.AskSig != ""
	case "cosmos.auction.v1.Auction.bid_sig":
		return x.BidSig != ""
	case "cosmos.auction.v1.Auction.seller_sig":
		return x.SellerSig != ""
	case "cosmos.auction.v1.Auction.confirmed_height":
		return x.ConfirmedHeight != int64(0)
	case "cosmos.auction.v1.Auction.tx_hash":
		return x.TxHash != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmos.auction.v1.Auction"))
		}
		panic(fmt.Errorf("message cosmos.auction.v1.Auction does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Auction) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "cosmos.auction.v1.Auction.auction_id":
		x.AuctionId = ""
	case "cosmos.auction.v1.Auction.seller":
		x.Seller = ""
	case "cosmos.auction.v1.Auction.winner":
		x.Winner = ""
	case "cosmos.auction.v1.Auction.price":
		x.Price = ""
	case "cosmos.auction.v1.Auction.denom":
		x.Denom = ""
	case "cosmos.auction.v1.Auction.end_height":
		x.EndHeight = int64(0)
	case "cosmos.auction.v1.Auction.ask_sig":
		x.AskSig = ""
	case "cosmos.auction.v1.Auction.bid_sig":
		x.BidSig = ""
	case "cosmos.auction.v1.Auction.seller_sig":
		x.SellerSig = ""
	case "cosmos.auction.v1.Auction.confirmed_height":
		x.ConfirmedHeight = int64(0)
	case "cosmos.auction.v1.Auction.tx_hash":
		x.TxHash = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmos.auction.v1.Auction"))
		}
		panic(fmt.Errorf("message cosmos.auction.v1.Auction does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Auction) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "cosmos.auction.v1.Auction.auction_id":
		value := x.AuctionId
		return protoreflect.ValueOfString(value)
	case "cosmos.auction.v1.Auction.seller":
		value := x.Seller
		return protoreflect.ValueOfString(value)
	case "cosmos.auction.v1.Auction.winner":
		value := x.Winner
		return protoreflect.ValueOfString(value)
	case "cosmos.auction.v1.Auction.price":
		value := x.Price
		return protoreflect.ValueOfString(value)
	case "cosmos.auction.v1.Auction.denom":
		value := x.Denom
		return protoreflect.ValueOfString(value)
	case "cosmos.auction.v1.Auction.end_height":
		value := x.EndHeight
		return protoreflect.ValueOfInt64(value)
	case "cosmos.auction.v1.Auction.ask_sig":
		value := x.AskSig
		return protoreflect.ValueOfString(value)
	case "cosmos.auction.v1.Auction.bid_sig":
		value := x.BidSig
		return protoreflect.ValueOfString(value)
	case "cosmos.auction.v1.Auction.seller_sig":
		value := x.SellerSig
		return protoreflect.ValueOfString(value)
	case "cosmos.auction.v1.Auction.confirmed_height":
		value := x.ConfirmedHeight
		return protoreflect.ValueOfInt64(value)
	case "cosmos.auction.v1.Auction.tx_hash":
		value := x.TxHash
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmos.auction.v1.Auction"))
		}
		panic(fmt.Errorf("message cosmos.auction.v1.Auction does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Auction) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "cosmos.auction.v1.Auction.auction_id":
		x.AuctionId = value.Interface().(string)
	case "cosmos.auction.v1.Auction.seller":
		x.Seller = value.Interface().(string)
	case "cosmos.auction.v1.Auction.winner":
		x.Winner = value.Interface().(string)
	case "cosmos.auction.v1.Auction.price":
		x.Price = value.Interface().(string)
	case "cosmos.auction.v1.Auction.denom":
		x.Denom = value.Interface().(string)
	case "cosmos.auction.v1.Auction.end_height":
		x.EndHeight = value.Int()
	case "cosmos.auction.v1.Auction.ask_sig":
		x.AskSig = value.Interface().(string)
	case "cosmos.auction.v1.Auction.bid_sig":
		x.BidSig = value.Interface().(string)
	case "cosmos.auction.v1.Auction.seller_sig":
		x.SellerSig = value.Interface().(string)
	case "cosmos.auction.v1.Auction.confirmed_height":
		x.ConfirmedHeight = value.Int()
	case "cosmos.auction.v1.Auction.tx_hash":
		x.TxHash = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmos.auction.v1.Auction"))
		}
		panic(fmt.Errorf("message cosmos.auction.v1.Auction does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Auction) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "cosmos.auction.v1.Auction.auction_id":
		panic(fmt.Errorf("field auction_id of message cosmos.auction.v1.Auction is not mutable"))
	case "cosmos.auction.v1.Auction.seller":
		panic(fmt.Errorf("field seller of message cosmos.auction.v1.Auction is not mutable"))
	case "cosmos.auction.v1.Auction.winner":
		panic(fmt.Errorf("field winner of message cosmos.auction.v1.Auction is not mutable"))
	case "cosmos.auction.v1.Auction.price":
		panic(fmt.Errorf("field price of message cosmos.auction.v1.Auction is not mutable"))
	case "cosmos.auction.v1.Auction.denom":
		panic(fmt.Errorf("field denom of message cosmos.auction.v1.Auction is not mutable"))
	case "cosmos.auction.v1.Auction.end_height":
		panic(fmt.Errorf("field end_height of message cosmos.auction.v1.Auction is not mutable"))
	case "cosmos.auction.v1.Auction.ask_sig":
		panic(fmt.Errorf("field ask_sig of message cosmos.auction.v1.Auction is not mutable"))
	case "cosmos.auction.v1.Auction.bid_sig":
		panic(fmt.Errorf("field bid_sig of message cosmos.auction.v1.Auction is not mutable"))
	case "cosmos.auction.v1.Auction.seller_sig":
		panic(fmt.Errorf("field seller_sig of message cosmos.auction.v1.Auction is not mutable"))
	case "cosmos.auction.v1.Auction.confirmed_height":
		panic(fmt.Errorf("field confirmed_height of message cosmos.auction.v1.Auction is not mutable"))
	case "cosmos.auction.v1.Auction.tx_hash":
		panic(fmt.Errorf("field tx_hash of message cosmos.auction.v1.Auction is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmos.auction.v1.Auction"))
		}
		panic(fmt.Errorf("message cosmos.auction.v1.Auction does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Auction) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "cosmos.auction.v1.Auction.auction_id":
		return protoreflect.ValueOfString("")
	case "cosmos.auction.v1.Auction.seller":
		return protoreflect.ValueOfString("")
	case "cosmos.auction.v1.Auction.winner":
		return protoreflect.ValueOfString("")
	case "cosmos.auction.v1.Auction.price":
		return protoreflect.ValueOfString("")
	case "cosmos.auction.v1.Auction.denom":
		return protoreflect.ValueOfString("")
	case "cosmos.auction.v1.Auction.end_height":
		return protoreflect.ValueOfInt64(int64(0))
	case "cosmos.auction.v1.Auction.ask_sig":
		return protoreflect.ValueOfString("")
	case "cosmos.auction.v1.Auction.bid_sig":
		return protoreflect.ValueOfString("")
	case "cosmos.auction.v1.Auction.seller_sig":
		return protoreflect.ValueOfString("")
	case "cosmos.auction.v1.Auction.confirmed_height":
		return protoreflect.ValueOfInt64(int64(0))
	case "cosmos.auction.v1.Auction.tx_hash":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: cosmos.auction.v1.Auction"))
		}
		panic(fmt.Errorf("message cosmos.auction.v1.Auction does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Auction) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in cosmos.auction.v1.Auction", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Auction) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Auction) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Auction) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Auction) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Auction)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.AuctionId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Seller)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Winner)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Price)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Denom)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.EndHeight != 0 {
			n += 1 + runtime.Sov(uint64(x.EndHeight))
		}
		l = len(x.AskSig)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.BidSig)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SellerSig)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.ConfirmedHeight != 0 {
			n += 1 + runtime.Sov(uint64(x.ConfirmedHeight))
		}
		l = len(x.TxHash)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Auction)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.TxHash) > 0 {
			i -= len(x.TxHash)
			copy(dAtA[i:], x.TxHash)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.TxHash)))
			i--
			dAtA[i] = 0x5a
		}
		if x.ConfirmedHeight != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ConfirmedHeight))
			i--
			dAtA[i] = 0x50
		}
		if len(x.SellerSig) > 0 {
			i -= len(x.SellerSig)
			copy(dAtA[i:], x.SellerSig)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SellerSig)))
			i--
			dAtA[i] = 0x4a
		}
		if len(x.BidSig) > 0 {
			i -= len(x.BidSig)
			copy(dAtA[i:], x.BidSig)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.BidSig)))
			i--
			dAtA[i] = 0x42
		}
		if len(x.AskSig) > 0 {
			i -= len(x.AskSig)
			copy(dAtA[i:], x.AskSig)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AskSig)))
			i--
			dAtA[i] = 0x3a
		}
		if x.EndHeight != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.EndHeight))
			i--
			dAtA[i] = 0x30
		}
		if len(x.Denom) > 0 {
			i -= len(x.Denom)
			copy(dAtA[i:], x.Denom)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Denom)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.Price) > 0 {
			i -= len(x.Price)
			copy(dAtA[i:], x.Price)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Price)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Winner) > 0 {
			i -= len(x.Winner)
			copy(dAtA[i:], x.Winner)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Winner)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Seller) > 0 {
			i -= len(x.Seller)
			copy(dAtA[i:], x.Seller)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Seller)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.AuctionId) > 0 {
			i -= len(x.AuctionId)
			copy(dAtA[i:], x.AuctionId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.AuctionId)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Auction)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Auction: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Auction: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AuctionId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Seller", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Seller = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Winner", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Winner = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Price = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Denom = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field EndHeight", wireType)
				}
				x.EndHeight = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.EndHeight |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field AskSig", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.AskSig = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BidSig", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.BidSig = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 9:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SellerSig", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SellerSig = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 10:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ConfirmedHeight", wireType)
				}
				x.ConfirmedHeight = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ConfirmedHeight |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 11:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.TxHash = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: cosmos/auction/v1/auction.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Auction stores the confirmed auction result on-chain.
type Auction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuctionId       string `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Seller          string `protobuf:"bytes,2,opt,name=seller,proto3" json:"seller,omitempty"`
	Winner          string `protobuf:"bytes,3,opt,name=winner,proto3" json:"winner,omitempty"`
	Price           string `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Denom           string `protobuf:"bytes,5,opt,name=denom,proto3" json:"denom,omitempty"`
	EndHeight       int64  `protobuf:"varint,6,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	AskSig          string `protobuf:"bytes,7,opt,name=ask_sig,json=askSig,proto3" json:"ask_sig,omitempty"`
	BidSig          string `protobuf:"bytes,8,opt,name=bid_sig,json=bidSig,proto3" json:"bid_sig,omitempty"`
	SellerSig       string `protobuf:"bytes,9,opt,name=seller_sig,json=sellerSig,proto3" json:"seller_sig,omitempty"`
	ConfirmedHeight int64  `protobuf:"varint,10,opt,name=confirmed_height,json=confirmedHeight,proto3" json:"confirmed_height,omitempty"`
	TxHash          string `protobuf:"bytes,11,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
}

func (x *Auction) Reset() {
	*x = Auction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cosmos_auction_v1_auction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auction) ProtoMessage() {}

// Deprecated: Use Auction.ProtoReflect.Descriptor instead.
func (*Auction) Descriptor() ([]byte, []int) {
	return file_cosmos_auction_v1_auction_proto_rawDescGZIP(), []int{0}
}

func (x *Auction) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *Auction) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *Auction) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *Auction) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Auction) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *Auction) GetEndHeight() int64 {
	if x != nil {
		return x.EndHeight
	}
	return 0
}

func (x *Auction) GetAskSig() string {
	if x != nil {
		return x.AskSig
	}
	return ""
}

func (x *Auction) GetBidSig() string {
	if x != nil {
		return x.BidSig
	}
	return ""
}

func (x *Auction) GetSellerSig() string {
	if x != nil {
		return x.SellerSig
	}
	return ""
}

func (x *Auction) GetConfirmedHeight() int64 {
	if x != nil {
		return x.ConfirmedHeight
	}
	return 0
}

func (x *Auction) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

var File_cosmos_auction_v1_auction_proto protoreflect.FileDescriptor

var file_cosmos_auction_v1_auction_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2f, 0x76, 0x31, 0x2f, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbe, 0x02, 0x0a, 0x07, 0x41,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x77, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77,
	0x69, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64,
	0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x65, 0x6e, 0x6f,
	0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x64, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x61, 0x73, 0x6b, 0x5f, 0x73, 0x69, 0x67, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x61, 0x73, 0x6b, 0x53, 0x69, 0x67, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x69, 0x64,
	0x5f, 0x73, 0x69, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x69, 0x64, 0x53,
	0x69, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x73, 0x69, 0x67,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x69,
	0x67, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x5f, 0x68,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x78, 0x48, 0x61, 0x73, 0x68, 0x3a, 0x04, 0x88, 0xa0, 0x1f, 0x00, 0x42, 0xb9, 0x01, 0x0a, 0x15,
	0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x61, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2c, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b,
	0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2f, 0x61,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x43, 0x41, 0x58, 0xaa, 0x02, 0x11, 0x43, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x2e, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x11,
	0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5c, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5c, 0x56,
	0x31, 0xe2, 0x02, 0x1d, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5c, 0x41, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x13, 0x43, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x3a, 0x3a, 0x41, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cosmos_auction_v1_auction_proto_rawDescOnce sync.Once
	file_cosmos_auction_v1_auction_proto_rawDescData = file_cosmos_auction_v1_auction_proto_rawDesc
)

func file_cosmos_auction_v1_auction_proto_rawDescGZIP() []byte {
	file_cosmos_auction_v1_auction_proto_rawDescOnce.Do(func() {
		file_cosmos_auction_v1_auction_proto_rawDescData = protoimpl.X.CompressGZIP(file_cosmos_auction_v1_auction_proto_rawDescData)
	})
	return file_cosmos_auction_v1_auction_proto_rawDescData
}

var file_cosmos_auction_v1_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cosmos_auction_v1_auction_proto_goTypes = []interface{}{
	(*Auction)(nil), // 0: cosmos.auction.v1.Auction
}
var file_cosmos_auction_v1_auction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cosmos_auction_v1_auction_proto_init() }
func file_cosmos_auction_v1_auction_proto_init() {
	if File_cosmos_auction_v1_auction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cosmos_auction_v1_auction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cosmos_auction_v1_auction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cosmos_auction_v1_auction_proto_goTypes,
		DependencyIndexes: file_cosmos_auction_v1_auction_proto_depIdxs,
		MessageInfos:      file_cosmos_auction_v1_auction_proto_msgTypes,
	}.Build()
	File_cosmos_auction_v1_auction_proto = out.File
	file_cosmos_auction_v1_auction_proto_rawDesc = nil
	file_cosmos_auction_v1_auction_proto_goTypes = nil
	file_cosmos_auction_v1_auction_proto_depIdxs = nil
}
