// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: match/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSubmitMatchCertificate is the tx payload for certificate submission.
type MsgSubmitMatchCertificate struct {
	Submitter   string           `protobuf:"bytes,1,opt,name=submitter,proto3" json:"submitter,omitempty"`
	Certificate MatchCertificate `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate"`
}

func (m *MsgSubmitMatchCertificate) Reset()         { *m = MsgSubmitMatchCertificate{} }
func (m *MsgSubmitMatchCertificate) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitMatchCertificate) ProtoMessage()    {}
func (*MsgSubmitMatchCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_230860293435ce13, []int{0}
}
func (m *MsgSubmitMatchCertificate) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitMatchCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitMatchCertificate.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitMatchCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitMatchCertificate.Merge(m, src)
}
func (m *MsgSubmitMatchCertificate) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitMatchCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitMatchCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitMatchCertificate proto.InternalMessageInfo

func (m *MsgSubmitMatchCertificate) GetSubmitter() string {
	if m != nil {
		return m.Submitter
	}
	return ""
}

func (m *MsgSubmitMatchCertificate) GetCertificate() MatchCertificate {
	if m != nil {
		return m.Certificate
	}
	return MatchCertificate{}
}

// MsgSubmitMatchCertificateResponse is the tx result payload.
type MsgSubmitMatchCertificateResponse struct {
	MatchId         string `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	CertificateHash []byte `protobuf:"bytes,2,opt,name=certificate_hash,json=certificateHash,proto3" json:"certificate_hash,omitempty"`
	ReplayKey       string `protobuf:"bytes,3,opt,name=replay_key,json=replayKey,proto3" json:"replay_key,omitempty"`
}

func (m *MsgSubmitMatchCertificateResponse) Reset()         { *m = MsgSubmitMatchCertificateResponse{} }
func (m *MsgSubmitMatchCertificateResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSubmitMatchCertificateResponse) ProtoMessage()    {}
func (*MsgSubmitMatchCertificateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_230860293435ce13, []int{1}
}
func (m *MsgSubmitMatchCertificateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSubmitMatchCertificateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSubmitMatchCertificateResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSubmitMatchCertificateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSubmitMatchCertificateResponse.Merge(m, src)
}
func (m *MsgSubmitMatchCertificateResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSubmitMatchCertificateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSubmitMatchCertificateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSubmitMatchCertificateResponse proto.InternalMessageInfo

func (m *MsgSubmitMatchCertificateResponse) GetMatchId() string {
	if m != nil {
		return m.MatchId
	}
	return ""
}

func (m *MsgSubmitMatchCertificateResponse) GetCertificateHash() []byte {
	if m != nil {
		return m.CertificateHash
	}
	return nil
}

func (m *MsgSubmitMatchCertificateResponse) GetReplayKey() string {
	if m != nil {
		return m.ReplayKey
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgSubmitMatchCertificate)(nil), "match.v1.MsgSubmitMatchCertificate")
	proto.RegisterType((*MsgSubmitMatchCertificateResponse)(nil), "match.v1.MsgSubmitMatchCertificateResponse")
}

func init() { proto.RegisterFile("match/v1/tx.proto", fileDescriptor_230860293435ce13) }

var fileDescriptor_230860293435ce13 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x4d, 0x2c, 0x49,
	0xce, 0xd0, 0x2f, 0x33, 0xd4, 0x2f, 0xa9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00,
	0x0b, 0xe9, 0x95, 0x19, 0x4a, 0x09, 0x26, 0xe6, 0x66, 0xe6, 0xe5, 0xeb, 0x83, 0x49, 0x88, 0xa4,
	0x94, 0x78, 0x72, 0x7e, 0x71, 0x6e, 0x7e, 0xb1, 0x7e, 0x6e, 0x71, 0x3a, 0x48, 0x53, 0x6e, 0x71,
	0x3a, 0x54, 0x42, 0x12, 0x22, 0x11, 0x0f, 0xe6, 0xe9, 0x43, 0x38, 0x50, 0x29, 0x91, 0xf4, 0xfc,
	0xf4, 0x7c, 0x88, 0x38, 0x88, 0x05, 0x13, 0x45, 0xd8, 0x5c, 0x59, 0x90, 0x0a, 0x55, 0xab, 0x74,
	0x97, 0x91, 0x4b, 0xd2, 0xb7, 0x38, 0x3d, 0xb8, 0x34, 0x29, 0x37, 0xb3, 0xc4, 0x17, 0xa4, 0xc2,
	0x39, 0xb5, 0xa8, 0x24, 0x33, 0x2d, 0x33, 0x39, 0xb1, 0x24, 0x55, 0xc8, 0x8c, 0x8b, 0xb3, 0x18,
	0x2c, 0x53, 0x92, 0x5a, 0x24, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0xe9, 0x24, 0x71, 0x69, 0x8b, 0xae,
	0x08, 0xd4, 0x3a, 0xc7, 0x94, 0x94, 0xa2, 0xd4, 0xe2, 0xe2, 0xe0, 0x92, 0xa2, 0xcc, 0xbc, 0xf4,
	0x20, 0x84, 0x52, 0x21, 0x77, 0x2e, 0xee, 0x64, 0x84, 0x31, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc,
	0x46, 0x52, 0x7a, 0x30, 0x8f, 0xea, 0xa1, 0x5b, 0xe4, 0xc4, 0x79, 0xe2, 0x9e, 0x3c, 0xc3, 0x8a,
	0xe7, 0x1b, 0xb4, 0x18, 0x83, 0x90, 0x75, 0x5a, 0xd9, 0x37, 0x3d, 0xdf, 0xa0, 0x85, 0x30, 0xb8,
	0xeb, 0xf9, 0x06, 0x2d, 0x1d, 0x68, 0x88, 0xa4, 0x96, 0xe5, 0xea, 0x57, 0xe8, 0x43, 0x3c, 0x85,
	0xd3, 0x07, 0x4a, 0x1d, 0x8c, 0x5c, 0x8a, 0x38, 0x65, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x85, 0x24, 0xb9, 0x20, 0x91, 0x10, 0x9f, 0x99, 0x02, 0xf1, 0x66, 0x10, 0x3b, 0x98, 0xef,
	0x99, 0x22, 0xa4, 0xc9, 0x25, 0x80, 0xe4, 0xa0, 0xf8, 0x8c, 0xc4, 0xe2, 0x0c, 0xb0, 0x7f, 0x78,
	0x82, 0xf8, 0x91, 0xc4, 0x3d, 0x12, 0x8b, 0x33, 0x84, 0x64, 0xb9, 0xb8, 0x8a, 0x52, 0x0b, 0x72,
	0x12, 0x2b, 0xe3, 0xb3, 0x53, 0x2b, 0x25, 0x98, 0xc1, 0xe6, 0x70, 0x42, 0x44, 0xbc, 0x53, 0x2b,
	0x8d, 0x2a, 0xb8, 0x98, 0x7d, 0x8b, 0xd3, 0x85, 0xb2, 0xb8, 0xc4, 0x70, 0x84, 0xb6, 0x32, 0x52,
	0x00, 0xe1, 0x72, 0xb2, 0x94, 0x36, 0x11, 0x8a, 0x60, 0xfe, 0x92, 0x62, 0x6d, 0x00, 0x05, 0xa9,
	0x93, 0xed, 0x89, 0x47, 0x72, 0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0x38, 0xe1,
	0xb1, 0x1c, 0xc3, 0x85, 0xc7, 0x72, 0x0c, 0x37, 0x1e, 0xcb, 0x31, 0x44, 0x29, 0xa7, 0x67, 0x96,
	0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7, 0xea, 0x63, 0x09, 0x57, 0x70, 0x4a, 0x49, 0x62, 0x03,
	0x27, 0x15, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5f, 0xec, 0xce, 0x00, 0xbc, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// SubmitMatchCertificate verifies signatures and records a match.
	SubmitMatchCertificate(ctx context.Context, in *MsgSubmitMatchCertificate, opts ...grpc.CallOption) (*MsgSubmitMatchCertificateResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SubmitMatchCertificate(ctx context.Context, in *MsgSubmitMatchCertificate, opts ...grpc.CallOption) (*MsgSubmitMatchCertificateResponse, error) {
	out := new(MsgSubmitMatchCertificateResponse)
	err := c.cc.Invoke(ctx, "/match.v1.Msg/SubmitMatchCertificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// SubmitMatchCertificate verifies signatures and records a match.
	SubmitMatchCertificate(context.Context, *MsgSubmitMatchCertificate) (*MsgSubmitMatchCertificateResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SubmitMatchCertificate(ctx context.Context, req *MsgSubmitMatchCertificate) (*MsgSubmitMatchCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitMatchCertificate not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SubmitMatchCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSubmitMatchCertificate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SubmitMatchCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/match.v1.Msg/SubmitMatchCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SubmitMatchCertificate(ctx, req.(*MsgSubmitMatchCertificate))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "match.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitMatchCertificate",
			Handler:    _Msg_SubmitMatchCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "match/v1/tx.proto",
}

func (m *MsgSubmitMatchCertificate) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitMatchCertificate) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitMatchCertificate) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Certificate.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Submitter) > 0 {
		i -= len(m.Submitter)
		copy(dAtA[i:], m.Submitter)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Submitter)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSubmitMatchCertificateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSubmitMatchCertificateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSubmitMatchCertificateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReplayKey) > 0 {
		i -= len(m.ReplayKey)
		copy(dAtA[i:], m.ReplayKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ReplayKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CertificateHash) > 0 {
		i -= len(m.CertificateHash)
		copy(dAtA[i:], m.CertificateHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.CertificateHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MatchId) > 0 {
		i -= len(m.MatchId)
		copy(dAtA[i:], m.MatchId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.MatchId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSubmitMatchCertificate) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Submitter)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Certificate.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgSubmitMatchCertificateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MatchId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.CertificateHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ReplayKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSubmitMatchCertificate) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitMatchCertificate: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitMatchCertificate: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Submitter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Submitter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Certificate", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Certificate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSubmitMatchCertificateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSubmitMatchCertificateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSubmitMatchCertificateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MatchId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MatchId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CertificateHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CertificateHash = append(m.CertificateHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CertificateHash == nil {
				m.CertificateHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplayKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReplayKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
